# Generated by Django 5.2.6 on 2025-10-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='UserServices.modules'),
        ),
    ]
