# Generated by Django 5.2.6 on 2025-10-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0004_alter_modules_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserServices.modules'),
        ),
    ]
