# Generated by Django 5.2.6 on 2025-10-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0005_alter_modules_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
