# Generated by Django 5.2.6 on 2025-10-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0006_rename_parent_id_modules_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='parent',
        ),
        migrations.AddField(
            model_name='modules',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='UserServices.modules'),
        ),
    ]
