# Generated by Django 5.2.6 on 2025-10-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0007_remove_modules_parent_modules_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_activity_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_user_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, db_column='added_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
