# Generated by Django 5.2.6 on 2025-10-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryServices', '0002_initial'),
        ('OrderServices', '0002_initial'),
        ('ProductServices', '0003_alter_categories_added_by_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, db_column='added_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id_inventory', to='ProductServices.products'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_order_id',
            field=models.ForeignKey(blank=True, db_column='purchase_order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_id_inventory', to='OrderServices.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_order_item_id',
            field=models.ForeignKey(blank=True, db_column='purchase_order_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item_id_inventory', to='OrderServices.purchaseorderitems'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_order_item_inwarded_item_id',
            field=models.ForeignKey(blank=True, db_column='purchase_order_item_inwarded_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item_inwarded_item_id_inventory', to='OrderServices.purchaseorderiteminwardedlog'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='rack_shelf_floor_id',
            field=models.ForeignKey(blank=True, db_column='rack_shelf_floor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_shelf_floor_id_inventory', to='InventoryServices.rackandshelvesandfloor'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id_inventory', to='InventoryServices.warehouse'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, db_column='added_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_inventory_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_inventory_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='inventory_id',
            field=models.ForeignKey(blank=True, db_column='inventory_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_id_inventory_log', to='InventoryServices.inventory'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='po_id',
            field=models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_id_inventory_log', to='OrderServices.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='rack_shelf_floor_id',
            field=models.ForeignKey(blank=True, db_column='rack_shelf_floor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_shelf_floor_id_inventory_log', to='InventoryServices.rackandshelvesandfloor'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='so_id',
            field=models.ForeignKey(blank=True, db_column='so_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_id_inventory_log', to='OrderServices.salesorder'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id_inventory_log', to='InventoryServices.warehouse'),
        ),
        migrations.AlterField(
            model_name='rackandshelvesandfloor',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, db_column='added_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_rack_shelf_floor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rackandshelvesandfloor',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_rack_shelf_floor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rackandshelvesandfloor',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id_rack_shelf_floor', to='InventoryServices.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, db_column='added_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_warhouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_warhouse', to=settings.AUTH_USER_MODEL),
        ),
    ]
