# Generated by Django 5.2.6 on 2025-10-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, db_column='added_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductServices.categories'),
        ),
        migrations.AlterField(
            model_name='productquestions',
            name='answer_user_id',
            field=models.ForeignKey(blank=True, db_column='answer_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_by_user_id_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productquestions',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productquestions',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id_questions', to='ProductServices.products'),
        ),
        migrations.AlterField(
            model_name='productquestions',
            name='question_user_id',
            field=models.ForeignKey(blank=True, db_column='question_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_by_user_id_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id_reviews', to='ProductServices.products'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='review_user_id',
            field=models.ForeignKey(blank=True, db_column='review_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, db_column='added_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id_products', to='ProductServices.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
