# Generated by Django 5.2.6 on 2025-10-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryServices', '0003_alter_inventory_added_by_user_id_and_more'),
        ('OrderServices', '0002_initial'),
        ('ProductServices', '0003_alter_categories_added_by_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='approved_by_user_id',
            field=models.ForeignKey(blank=True, db_column='approved_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='cancelled_by_user_id',
            field=models.ForeignKey(blank=True, db_column='cancelled_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_id',
            field=models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, db_column='updated_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse_id',
            field=models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id', to='InventoryServices.warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseorderinwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_inwarded_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderinwardedlog',
            name='inwarded_by_user_id',
            field=models.ForeignKey(blank=True, db_column='inwarded_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inwarded_by_user_id_purchase_order_items_inwarded_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderinwardedlog',
            name='po_id',
            field=models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_item_id', to='OrderServices.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderinwardedlog',
            name='received_by_user_id',
            field=models.ForeignKey(blank=True, db_column='received_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_by_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderinwardedlog',
            name='returned_by_user_id',
            field=models.ForeignKey(blank=True, db_column='returned_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_by_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderiteminwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_purcahse_order_id_inwarded_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderiteminwardedlog',
            name='po_inward_id',
            field=models.ForeignKey(blank=True, db_column='po_inward_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_item_id_inwarded_log_po_inwarded', to='OrderServices.purchaseorderinwardedlog'),
        ),
        migrations.AlterField(
            model_name='purchaseorderiteminwardedlog',
            name='po_item_id',
            field=models.ForeignKey(blank=True, db_column='po_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_item_id_inwarded_log', to='OrderServices.purchaseorderitems'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_purchase_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='po_id',
            field=models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_id_purchase_order_items', to='OrderServices.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_id_purchase_order_items', to='ProductServices.products'),
        ),
        migrations.AlterField(
            model_name='purchaseorderlogs',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_purchase_order_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderlogs',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_purchase_order_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderlogs',
            name='po_id',
            field=models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_id_purchase_order_logs', to='OrderServices.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='approved_by_user_id',
            field=models.ForeignKey(blank=True, db_column='approved_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_user_id_sales_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='cancelled_by_user_id',
            field=models.ForeignKey(blank=True, db_column='cancelled_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user_id_sales_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_sales_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_id',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_id_sales_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_sales_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='last_updated_by_user_id',
            field=models.ForeignKey(blank=True, db_column='last_updated_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_updated_by_user_id_sales_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, db_column='updated_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user_id_sales_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorderitemoutwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_sales_order_id_outwarded_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorderitemoutwardedlog',
            name='so_item_id',
            field=models.ForeignKey(blank=True, db_column='so_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_item_id_outwarded_log', to='OrderServices.salesorderorderitems'),
        ),
        migrations.AlterField(
            model_name='salesorderitemoutwardedlog',
            name='so_outwarded_id',
            field=models.ForeignKey(blank=True, db_column='so_outwarded_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_item_id_outwarded_log_outwarded_id', to='OrderServices.salesorderoutwardedlog'),
        ),
        migrations.AlterField(
            model_name='salesorderlogs',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_sales_order_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorderlogs',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_sales_order_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorderlogs',
            name='so_id',
            field=models.ForeignKey(blank=True, db_column='so_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_id_sales_order_logs', to='OrderServices.salesorder'),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_so_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id_so_order_items', to='ProductServices.products'),
        ),
        migrations.AlterField(
            model_name='salesorderorderitems',
            name='so_id',
            field=models.ForeignKey(blank=True, db_column='so_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_id_so_order_items', to='OrderServices.salesorder'),
        ),
        migrations.AlterField(
            model_name='salesorderoutwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, db_column='domain_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_outwarded_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorderoutwardedlog',
            name='outwarded_by_user_id',
            field=models.ForeignKey(blank=True, db_column='outwarded_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outwarded_by_user_id_so_order_items_outwarded_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorderoutwardedlog',
            name='returned_by_user_id',
            field=models.ForeignKey(blank=True, db_column='returned_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_by_user_id_sales_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorderoutwardedlog',
            name='send_by_user_id',
            field=models.ForeignKey(blank=True, db_column='send_by_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_by_user_id_purchase_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorderoutwardedlog',
            name='so_id',
            field=models.ForeignKey(blank=True, db_column='so_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_order_id_outwarded_log', to='OrderServices.salesorder'),
        ),
    ]
